### ISSUE TITLE
Multiple event handler capture zones clashing

### ISSUE THREAD

**Issue by patrickoneill46** [mattlewis92/angular-resizable-element#37]
I have come across an issue if you have more than one resizable elements positioned on top of each other, the one dragging movement can resize more than one container.

This occurs if you click and start dragging at the intersection of two resizable elements (as shown in the attached screenshot) both resizable elements will start resizing.

![resizables](https://cloud.githubusercontent.com/assets/1260456/22337900/fe41f26e-e3dd-11e6-88f1-9fa7000d1734.png)

I am wondering if anyone has come across this already and can suggest a solution?

**Comment by mattlewis92** [comment]
This is by design, so that you could have 2 elements next to each other in a table header and resize both at the same time. The only workaround I can think of is to use the [drag handle feature](https://github.com/mattlewis92/angular-resizable-element/blob/master/demo/demo.component.ts#L38-L42) and disable resizing from the edges of each element.
