### ISSUE TITLE
Incoreect behavior of GhostElement in app with GoldenLayout

### ISSUE THREAD

**Issue by kicur** [mattlewis92/angular-resizable-element#59]
Hey,

I've built an application which uses Golden Layout.  There won't be anything interesting besides the fact that every time I tried to resize any div container it's layout being changed by some pixels in right and in the bottom.  You can see this on the example below:
![resizable](https://user-images.githubusercontent.com/16742800/27958638-64a9cb06-6324-11e7-89ab-b4823b86a12e.jpg)

I mean when I click on resizable edge, ghost element is shown 2px further from the right and from the bottom than original element. What is more such state is being saved after unclicking. 

Do you have any suggestions why it is happening?

**Comment by mattlewis92** [comment]
The ghostElement feature will never be able to work 100% of the time, I'd recommend that you don't use it and instead implement the resizing logic yourself, see https://github.com/mattlewis92/angular-resizable-element/issues/58#issuecomment-313405226 for more info.

The state isn't saved after finishing the resize because again you should implement this yourself in your app, if you have a look at the demo source you can see how this works: https://github.com/mattlewis92/angular-resizable-element/blob/master/demo/demo.component.ts#L59-L67

**Comment by kicur** [comment]
I implemented logic when resizing is finished. I've got width, height and other parameter from ResizeEvent and I applied them to resizable div. But unfortunately I need to do some maths with that parameters to be sure that original container is in wright place. Even if disable ghostElement the size of resizable div after event is finished is still longer about 2px in left and in the bottom. I think this is due to fact that there is a goldenLayout implementation because without that everything works properly.

So even if I implement new logic for ghost it might not resolve my problem :/

**Comment by kicur** [comment]
Anyway the solution for me should be eliminated this "jump" when I click on the resizable edge. For example in your DEMO when you click on the edge nothing happens but when I click on my edge ghost is displayed 2 px further from right and the bottom.
