### ISSUE TITLE
Moving the mouse without resizing triggers a whole lot of change detection cycles

### ISSUE THREAD

**Issue by marclerman** [mattlewis92/angular-resizable-element#65]
Hello,

We noticed this in our application. Even when we don't use the resize handle to resize anything, when the ResizableDirective is instantiated, moving the mouse is enough to trigger a very large amount of change detection cycles.

Would it at least be possible to have an @Input on the ResizableDirective that would just disable it?

Thanks!
Marc.

**Comment by mattlewis92** [comment]
That's odd, the mouse move listener should already be [ran outside of the angular zone](https://github.com/mattlewis92/angular-resizable-element/blob/master/src/resizable.directive.ts#L575) and not be triggering any change detection cycles. Are you definitely on the latest version of this lib? If so I'll do some digging and try and work out why change detection is still being ran.

**Comment by marclerman** [comment]
Yes, I do see in the code the calls to zone.runOutsideAngular. However, I still see lots of change detection cycles because of this.

Thanks very much in advance for looking into this.

**Comment by marclerman** [comment]
Hi @mattlewis92 , have you been able to reproduce the problem?
Thanks.

**Comment by mattlewis92** [comment]
I'm afraid I haven't had the time, been super busy lately.

**Comment by mattlewis92** [comment]
Ah I finally realised what was going on, the fix was pretty straight forward and involved moving the calls to runOutsideAngular inside the observable instance after its been subscribed to. Please give 1.2.2 a try, it should have much better perf now. Thanks a bunch for reporting this, it will give a nice perf boost to https://github.com/mattlewis92/angular-calendar as well 😄
